import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from './components/sidebar/Sidebar';
import Topbar from './components/topbar/Topbar';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <div className="wrapper">
          <Sidebar />
          <div className="flex flex-col w-full pt-5 pr-7">
            <Topbar />
            {children}
          </div>

        </div>
      </body>
    </html>
  );
}
